%==========================================================================
%
% c* and c** from Fajun's measuremts, unfortuantely, they were done in H2O
% and not D2O. Hence, in the future we should may perform the same set of
% experiments in D2O
%
%==========================================================================

% c*
c1 = [ ...
       10  0.5 0.1;
       20  1.0 0.2;
       50  4.0 1.0;
       80  5.0 0.2;
       100 7.0 1.0 ];
%c**
c2 = [ ...
       10  15  5;
       20  16  2;
       50  25  2;
       80  30  2;
       100 35  5 ];

%==========================================================================
%
% c* and c** from Fajun's measuremts, unfortuantely, they were done in H2O
% and not D2O. Hence, in the future we should may perform the same set of
% experiments in D2O
%
%==========================================================================

% [ p1, ...
%   dp1, ...
%   residuum1, ...
%   info1 ] = levenberg_marquardt_fit( c1( :, 1 ), ... 
%                                      c1( :, 2 ), ... 
%                                      c1( :, 3 ), ...
%                                      [ 1 1 ], ...         % start values
%                                      [ -inf -inf ], ...   % lower boundary 
%                                      [ inf inf ],...      % upper boundary 
%                                      0, ... 
%                                      'polynom' );   
%         
% [ p2, ...
%   dp2, ...
%   residuum2, ...
%   info2 ] = levenberg_marquardt_fit( c2( :, 1 ), ... 
%                                      c2( :, 2 ), ... 
%                                      c2( :, 3 ), ...
%                                      [ 1 1 ], ...         % start values
%                                      [ -inf -inf ], ...   % lower boundary 
%                                      [ inf inf ],...      % upper boundary 
%                                      0, ... 
%                                      'polynom' );   
                                 
%==========================================================================
%
% plot phase diagram
%
%==========================================================================

figure
hold on
set( gcf, 'color', 'white' )
set( gca, 'box', 'on' )

%plot( c1( :, 1 ), p1(1) + p1(2) * c1( :, 1 ), 'LineWidth', 2, 'Color', 'm' )
%plot( c2( :, 1 ), p2(1) + p2(2) * c2( :, 1 ), 'LineWidth', 2, 'Color', 'm' )

errorbar( c1(:,1), c1(:,2), c1(:,3), ...
          'o', ...
          'Color', [0.8 0.8  1],...
          'LineWidth', 1,...
          'MarkerEdgeColor', [0.6 0 0.7],...
          'MarkerFaceColor', [0.6 0 0.7],...
          'MarkerSize', 6 )
              
errorbar( c2(:,1), c2(:,2), c2(:,3),...
          'o', ...
          'Color', [0.8 0.8  1],...
          'LineWidth', 1,...
          'MarkerEdgeColor', [0.6 0 0.7],...
          'MarkerFaceColor', [0.6 0 0.7],...
          'MarkerSize', 6 )
      
xlabel( 'BSA concentration [mg/ml]', 'fontweight', 'b', 'fontsize', 14 )
ylabel( 'YCl_3 concentration [mM]', 'fontweight', 'b', 'fontsize', 14 )
