\input texinfo @c -*-texinfo-*-
@c This will be for the printing version of the manual
@c @input config-local.texi

@c -----------------------------------------------------------------------------
@c $Id: ool-ref.texi,v 1.17 2005/05/19 18:39:41 biloti Exp $
@c -----------------------------------------------------------------------------

@c %**start of header
@setfilename ool-ref.info
@settitle Open Optimization Library -- Reference Manual
@finalout

@ifset publish
@set frontcontents
@setchapternewpage odd
@end ifset
@c %**end of header

@dircategory Scientific software
@direntry
* ool-ref: (ool-ref).  Open Optimization Library -- Reference
@end direntry

@c How to use the math macros
@c ==========================
@c
@c For simple expressions, simply use the @math{} command, e.g.
@c
@c     @math{\exp(x)/(1+x^2)}
@c
@c but if the expression includes characters that need to be 'escaped'
@c in texinfo, like '{' or '}', or needs different output for TeX and info,
@c then use the following form,
@c
@c     blah blah blah @c{$y^{1+b} \le \pi$}
@c     @math{y^@{1+b@} <= \pi}
@c
@c The first part using @c{} must appear at the end of a line (it reads
@c up to the line end -- as far as texinfo is concerned it's actually
@c a 'comment').  The comment command @c has been modified to capture
@c a TeX expression which is output by the next @math.
@c
@c For ordinary comments use the @comment command.

@tex
% Mathematical macros taken from the GNU Calc Manual
% ==================================================
%
% Some special kludges to make TeX formatting prettier.
% Because makeinfo.c exists, we can't just define new commands.
% So instead, we take over little-used existing commands.
%
% Redefine @cite{text} to act like $text$ in regular TeX.
% Info will typeset this same as @samp{text}.
\gdef\goodtex{\tex \let\rm\goodrm \let\t\ttfont \turnoffactive}
\gdef\goodrm{\fam0\tenrm}
\gdef\math{\goodtex$\mathxxx}
\gdef\mathxxx#1{#1$\Etex}
\global\let\oldxrefX=\xrefX
\gdef\xrefX[#1]{\begingroup\let\math=\dfn\oldxrefX[#1]\endgroup}
%
% Redefine @i{text} to be equivalent to @cite{text}, i.e., to use math mode.
% This looks the same in TeX but omits the surrounding ` ' in Info.
%\global\let\i=\cite
%\global\let\math=\cite
%
% Redefine @c{tex-stuff} \n @whatever{info-stuff}.
\gdef\c{\futurelet\next\mycxxx}
\gdef\mycxxx{%
  \ifx\next\bgroup \goodtex\let\next\mycxxy
  \else\ifx\next\mindex \let\next\relax
  \else\ifx\next\kindex \let\next\relax
  \else\ifx\next\starindex \let\next\relax \else \let\next\comment
  \fi\fi\fi\fi \next
}
\gdef\mycxxy#1#2{#1\Etex\mycxxz}
\gdef\mycxxz#1{}
%
% Define \Hat to take over from \hat as an accent
\gdef\Hat{\mathaccent "705E}
%
\gdef\beforedisplay{\vskip-10pt}
\gdef\afterdisplay{\vskip-5pt}
\gdef\beforedisplayh{\vskip-25pt}
\gdef\afterdisplayh{\vskip-10pt}
%
\gdef\arcsec{\hbox{\rm arcsec}}
\gdef\arccsc{\hbox{\rm arccsc}}
\gdef\arccot{\hbox{\rm arccot}}
\gdef\sech{\hbox{\rm sech}}
\gdef\csch{\hbox{\rm csch}}
\gdef\coth{\hbox{\rm coth}}
\gdef\arcsinh{\hbox{\rm arcsinh}}
\gdef\arccosh{\hbox{\rm arccosh}}
\gdef\arctanh{\hbox{\rm arctanh}}
\gdef\arcsech{\hbox{\rm arcsech}}
\gdef\arccsch{\hbox{\rm arccsch}}
\gdef\arccoth{\hbox{\rm arccoth}}
%
\gdef\Re{\hbox{\rm Re}}
\gdef\Im{\hbox{\rm Im}}
\gdef\Sin{\hbox{\rm Sin}}
\gdef\Cos{\hbox{\rm Cos}}
\gdef\Log{\hbox{\rm Log}}
%
\gdef\erf{\hbox{\rm erf}}
\gdef\erfc{\hbox{\rm erfc}}
\gdef\sinc{\hbox{\rm sinc}}
@end tex

@include version-ref.texi
@set OOL @i{Open Optimization Library}

@iftex
@copying
Copyright @copyright{} 2005 The OOL Team.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with the
Invariant Sections being ``GNU General Public License'' and ``Free
Software Needs Free Documentation'', the Front-Cover text being ``A GNU
Manual'', and with the Back-Cover Text being (a) (see below).  A copy
of the license is included in the section entitled ``GNU Free
Documentation License''.

(a) The Back-Cover Text is: ``You have freedom to copy and modify this
GNU Manual, like GNU software.''

The Texinfo source for this manual may be obtained from
@code{http://ool.sourceforge.net}
@end copying
@end iftex

@titlepage
@title Open Optimization Library
@subtitle Reference Manual
@subtitle Edition @value{EDITION}, for OOL Version @value{VERSION}
@subtitle @value{UPDATED}

@author Ricardo Biloti
Federal University of Parana
@comment @email{biloti@@mat.ufpr.br}
@sp 1

@author Luis D'Afonseca
Thorus Scisoft
@comment @email{akiles@@thorus-scisoft.com.br}
@sp 1

@author Sergio Ventura
Federal University of Parana
@comment @email{ventura@@mat.ufpr.br}
@sp 1

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@ifset frontcontents
@contents
@end ifset

@ifnottex
@node Top, Introduction, (dir), (dir)
@top OOL

This file documents the @value{OOL} (OOL), a collection of numerical
routines for optimization.  It corresponds to release @value{VERSION}
of the library.

More information about OOL can be found at the project homepage,
@url{http://ool.sourceforge.net}.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License.
@end ifnottex

@menu
* Introduction::
* Using the library::
* Quick Start::
* Brief Theoretical Introduction::
* Constrained Optimization::
* Projected Gradient Method::
* Spectral Projected Gradient Method::
* Gencan Method::
* Tools::
* Contributors to OOL::
* Reporting Constants::
* Autoconf Macros::
* Free Software Needs Free Documentation::
* GNU General Public License::
* GNU Free Documentation License::
* Function Index::
* Parameter Index::              
* Type Index::
* Concept Index::
@end menu

@node  Introduction
@chapter Introduction
@include intro.texi

@node Using the library
@chapter Using the library
@cindex usage, compiling application programs
@include usage.texi

@comment @node Error Handling
@comment @chapter Error Handling
@comment @cindex error handling
@comment @include err.texi

@node Quick Start
@chapter Quick Start
@include quickstart.texi

@node Brief Theoretical Introduction
@chapter Brief Theoretical Introduction
@cindex theoretical introduction
@include theory.texi

@node Constrained Optimization
@chapter Constrained Optimization
@cindex constrained optimization
@include conmin.texi

@node Projected Gradient Method
@chapter Projected Gradient Method
@cindex Projected gradient method
@include pgrad.texi

@node Spectral Projected Gradient Method
@chapter Spectral Projected Gradient Method
@cindex Spectral projected gradient method
@include spg.texi

@node Gencan Method
@chapter Gencan Method
@cindex Gencan method
@include gencan.texi

@node Tools
@chapter Tools
@cindex tools
@cindex numerical differentiation tools
@include tools.texi

@c -----------------------------------------------------------------------------

@node Contributors to OOL
@appendix Contributors to OOL

(See the AUTHORS file in the distribution for up-to-date information.)

@table @strong
@item Ricardo Biloti
Conceived OOL, wrote the design document. Wrote the codes for the SPG
method and the numerical evaluation tools, as well as their
documentation.

@item Luis Alberto D'Afonseca
Wrote all the codes in the C/GSL format. Wrote the CONMIN library.

@item Sergio Ventura
Wrote the documentation, as well as the html page. Converted GENCAN
from Fortran 77 to C.

@item Iara da Cunha
Wrote the codes for the projected gradient method.

@end table

@c -----------------------------------------------------------------------------

@node Reporting Constants
@appendix Reporting Constants

When writing numerical functions in a program which also uses OOL code
you may find it convenient to adopt the same reporting conventions as
in the library.

@table @code
@item OOL_UNBOUNDEDF
Lower unbounded function.

@item OOL_INFEASIBLE
Infeasible point

@item OOL_FINNERIT
Too many inner iterations

@item OOL_FLSEARCH
Line search failed

@item OOL_FDDIR
Unable to find a descent direction
@end table

@c -----------------------------------------------------------------------------

@node Autoconf Macros
@appendix Autoconf Macros
@include autoconf.texi

@node Free Software Needs Free Documentation
@unnumbered Free Software Needs Free Documentation
@include freemanuals.texi

@node  GNU General Public License
@unnumbered GNU General Public License
@include gpl.texi

@node GNU Free Documentation License
@unnumbered GNU Free Documentation License
@include fdl.texi

@iftex
@normalbottom
@end iftex

@node Function Index
@unnumbered Function Index

@printindex fn

@node Parameter Index
@unnumbered Parameter Index

@printindex vr

@node Type Index
@unnumbered Type Index

@printindex tp

@node Concept Index
@unnumbered Concept Index

@printindex cp

@ifclear frontcontents
@comment Use @setchapternewpage odd to ensure that the contents starts
@comment on an odd page so that it can always be moved to the front when
@comment printing two-up.
@setchapternewpage odd
@contents
@end ifclear

@ifset extrablankpages
@comment final page must be blank for printed version
@page
@headings off
@*
@page
@*
@comment @page
@comment @*
@comment @page
@comment @*
@end ifset
@bye
